# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

# This workflow will install Deno then run `deno lint` and `deno test`.
# For more information see: https://github.com/denoland/setup-deno

name: Deno

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Setup repo
        uses: actions/checkout@v4

      - name: gcloud caching
        uses: actions/cache@v4
        with:
          path: ${{ runner.tool_cache }}/deno
          key: ${{ runner.os }}-deno

      - name: Setup Deno
        uses: denoland/setup-deno@v2
        with:
          deno-version-file: .tool-versions

      # - name: Verify formatting
      #   run: deno fmt --check
      #
      # - name: Run linter
      #   run: deno lint
      #
      # - name: Run tests
      #   run: deno test -A
